extends SceneTree

const Behavior = preload("res://host_behavior.gd")
var checks := 0
var failures: Array[String] = []
var acknowledgements: Array = []

func _initialize() -> void:
	var behavior = Behavior.new()
	behavior.configure(true, true)
	behavior.acknowledgement.connect(func(id: String, status: String, reason: String) -> void: acknowledgements.append([id, status, reason]))
	behavior.snapshot({"revision": 1, "busy": true})
	behavior.update(0.9)
	var mid_enter: float = behavior.sit_progress
	_check(mid_enter > 0.0 and mid_enter < 1.0, "busy begins an actual sit transition")
	behavior.snapshot({"revision": 0, "busy": false})
	_check(behavior.busy, "stale activity revision cannot change base posture")
	behavior.request({"request_id": "wave-busy", "name": "wave", "ttl_ms": 12000})
	_check(acknowledgements[-1][1] == "rejected", "full-body wave cannot reset a seated pose")
	behavior.snapshot({"revision": 2, "busy": false})
	behavior.update(0.1)
	_check(behavior.sit_progress < mid_enter and behavior.sit_progress > 0.0, "enter can reverse at the current pose")
	behavior.snapshot({"revision": 3, "busy": true})
	behavior.update(3.0)
	_check(behavior.sit_progress == 1.0, "resumed busy reaches stable seated posture")
	behavior.snapshot({"revision": 4, "busy": true, "active_turns": 2})
	behavior.update(0.1)
	behavior.snapshot({"revision": 5, "busy": true, "active_turns": 1})
	behavior.update(0.1)
	_check(behavior.busy and behavior.sit_progress == 1.0, "ending one of multiple turns does not exit busy")
	behavior.request({"request_id": "delete-work", "name": "delete.react", "ttl_ms": 12000})
	behavior.update(0.5)
	_check(behavior.sit_progress == 1.0 and behavior.head_pitch != 0.0, "delete overlay preserves seated base")
	var ack_count: int = acknowledgements.size()
	behavior.request({"request_id": "delete-work", "name": "delete.react", "ttl_ms": 12000})
	_check(acknowledgements.size() == ack_count, "duplicate request does not replay an event")
	behavior.update(0.8)
	_check(acknowledgements[-1][1] == "finished" and behavior.busy, "delete completes and returns to busy base")
	behavior.snapshot({"revision": 6, "busy": false})
	behavior.request({"request_id": "finish", "name": "work.finished", "ttl_ms": 12000})
	behavior.update(0.3)
	_check(behavior.sit_progress == 1.0 and behavior.action_name == "work.finished", "finished gaze pauses before rising")
	behavior.request({"request_id": "priority", "name": "delete.react", "ttl_ms": 12000})
	_check(acknowledgements[-2][0] == "finish" and acknowledgements[-2][1] == "interrupted", "delete interrupts lower-priority finished gaze")
	behavior.request({"request_id": "lower-priority", "name": "work.finished", "ttl_ms": 12000})
	_check(acknowledgements[-1][1] == "rejected" and behavior.action_id == "priority", "finished gaze cannot preempt active deletion")
	behavior.cancel({"request_id": "stale", "reason": "priority"})
	_check(behavior.action_id == "priority", "stale cancellation cannot affect current request")
	behavior.cancel({"request_id": "priority", "reason": "priority"})
	behavior.update(0.25)
	_check(behavior.action_name.is_empty() and behavior.sit_progress < 1.0, "cancellation releases overlay and continues recovery")
	behavior.request({"request_id": "ttl", "name": "delete.react", "ttl_ms": 100})
	behavior.update(0.11)
	_check(acknowledgements[-1][1] == "interrupted" and acknowledgements[-1][2] == "deadline", "TTL uses time since receipt")
	behavior.connection_lost()
	behavior.update(3.0)
	_check(not behavior.busy and behavior.sit_progress == 0.0, "disconnect recovers to idle")
	behavior.snapshot({"revision": 1, "busy": true})
	_check(behavior.busy, "new connection accepts a new revision epoch")
	behavior.update(3.0)
	behavior.snapshot({"revision": 2, "busy": false})
	behavior.request({"request_id": "finish-resume", "name": "work.finished", "ttl_ms": 12000})
	behavior.update(0.2)
	behavior.snapshot({"revision": 3, "busy": true, "active_turns": 1})
	behavior.update(0.1)
	_check(acknowledgements[-1][0] == "finish-resume" and acknowledgements[-1][1] == "interrupted" and behavior.busy and behavior.sit_progress == 1.0, "new turn interrupts finish and remains seated")
	behavior.snapshot({"revision": 4, "busy": false})
	behavior.update(3.0)
	behavior.request({"request_id": "ttl-stall", "name": "delete.react", "ttl_ms": 100})
	behavior.update(2.0)
	_check(acknowledgements[-1][1] == "interrupted" and acknowledgements[-1][2] == "deadline", "long frame cannot turn expired TTL into a success")
	var head_only = Behavior.new()
	head_only.configure(false, false)
	head_only.snapshot({"revision": 1, "busy": true})
	head_only.update(3.0)
	_check(head_only.state == "host-busy-standing" and head_only.sit_progress == 0.0, "limited rigs advertise and use a standing busy fallback")
	print(JSON.stringify({"checks": checks, "failures": failures, "status": "passed" if failures.is_empty() else "failed"}))
	quit(0 if failures.is_empty() else 1)

func _check(condition: bool, message: String) -> void:
	checks += 1
	if not condition:
		failures.append(message)
