"""Single approval entry for every Live2D motion.

One command renders the authored key poses and the full native sequence of a
clip, composes the review sheets and the loop GIF under art/live2d/review/,
and (with --validate) checks the captures for clipping and a drifting floor.

    python tools/review_motion.py grass
    python tools/review_motion.py busy-laptop --revision 3 --validate
    python tools/review_motion.py idle --no-render
    python tools/review_motion.py idle --draft

Use --draft for a new review: it preserves approved sheets, captures into a
fresh build/review-runs directory, and records source/deployment provenance.

The grass and seated-laptop sheets keep the exact layouts of the earlier
create_motion_review.py / create_laptop_review.py scripts, so the approved
artifacts can be regenerated byte for byte. Clips without keyframes (idle,
busy-stand, delete) get a frame sheet sampled from their rendered sequence plus
the loop GIF.

Captures come from build/DesktopCompanion.exe --render-motion / --review-motion,
which read build/assets/. Always run native captures, never generated art.
"""
import argparse
import json
import math
import subprocess
import sys
import time
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageFont, ImageStat
from review_session import deployment_snapshot, new_draft_profile, record_session, finish_session, write_session

# A full native capture runs for about a minute (software OpenGL manages only a
# few frames per second), so progress has to reach the caller line by line. A
# block-buffered stdout would hold every line until the process exits, and that
# silence is exactly what reads as a hang upstream.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(line_buffering=True)

ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / "build"
EXE = BUILD / "DesktopCompanion.exe"
MOTIONS = ROOT / "assets" / "motions"
OUT = ROOT / "art" / "live2d" / "review"
FONT_PATH = "C:/Windows/Fonts/msyh.ttc"

# Frame counts published by `--render-motion`; keep in sync with src/main.cpp.
# `name` is the CLI / artifact name, `render` is the --render-motion argument and
# `motion` is the data file (`assets/motions/<motion>.motion.json`); they differ
# only for the standing busy variant. `peaks` asks the sequence sheet to add the
# sharpest frame pairs (see compose_sequence); clips without it keep the layout
# of the sheets that were already approved.
CLIPS = {
    "grass": dict(name="grass", render="grass", motion="grass", frames=120, style="grass",
                  prefix="grass", sequence="build/motion-sequence", review="build/motion-review"),
    "busy-laptop": dict(name="busy-laptop", render="busy-laptop", motion="busy-laptop", frames=195,
                        style="laptop", prefix="busy-laptop",
                        sequence="build/laptop-v{revision}-sequence", review="build/laptop-v{revision}-review"),
    "idle": dict(name="idle", render="idle", motion="idle", frames=120, style="sequence", prefix="idle",
                  sequence="build/idle-sequence", review="build/idle-review"),
    "busy-stand": dict(name="busy-stand", render="busy", motion="busy-stand", frames=195,
                       style="sequence", prefix="busy-stand", peaks=2,
                       sequence="build/busy-stand-sequence", review="build/busy-stand-review"),
    "delete": dict(name="delete", render="delete", motion="delete", frames=None, style="sequence",
                   prefix="delete", peaks=2, sequence="build/delete-sequence",
                   review="build/delete-review"),
}
STEP_SECONDS = 1.0 / 15.0
ALPHA_THRESHOLD = 128

# Grass rig sweeps. The levels are the ones the grass approval sheet documents.
EYE_LEVELS = ("1", "0.75", "0.5", "0.25", "0")
ELBOW_LEVELS = (-35, 0, 55)
REACH_LEVELS = (0, 0.5, 1)
WRIST_LEVELS = (-25, 0, 25)
WRIST_POSES = (("举草", 55, 20, 0), ("前伸", 60, -20, 1), ("脸侧遮挡", 65, 55, 1))


def font(size):
    return ImageFont.truetype(FONT_PATH, size)


def output_folder(p):
    return p.get('output', OUT)


def review_label(p, legacy):
    if not p.get('draft'):
        return legacy
    status = load_motion(p['motion']).get('approval', 'pending')
    authored = '已批准' if status == 'approved' else '待审批'
    return f'动作数据{authored} / 本次草稿待复核'


def load_motion(name):
    return json.loads((MOTIONS / f"{name}.motion.json").read_text(encoding="utf8"))


def available_clips():
    # "busy" is the Native state alias for busy-stand, not a direct clip ID.
    discovered = {path.name.removesuffix('.motion.json') for path in MOTIONS.glob('*.motion.json')}
    return sorted(set(CLIPS) | (discovered - {'busy'}))


def motion_duration(motion):
    """Resolve duration as MotionClip does, including implicit endpoints."""
    duration = motion.get('duration', -1.0)
    if not duration > 0:
        endpoints = [key['time'] for key in motion.get('keyframes', [])]
        endpoints.extend(track[-1][0] for track in motion.get('tracks', {}).values() if track)
        endpoints.extend(pulse['end'] for pulses in motion.get('pulses', {}).values() for pulse in pulses)
        duration = max(endpoints, default=0.0)
    if not math.isfinite(duration) or duration <= 0:
        raise SystemExit('Motion needs a positive duration or timed keyframes/tracks/pulses.')
    return duration


def profile(clip, revision=None):
    """Resolve the capture directories, prefix and sheet style for a clip."""
    if clip not in available_clips():
        raise SystemExit(f"Unknown clip {clip!r}; known: {', '.join(available_clips())}")
    # New clips can be reviewed without teaching this CLI another hard-coded
    # name. Direct sampling reviews their curves, not yet their input/state flow.
    spec = CLIPS.get(clip, dict(name=clip, render=clip, motion=clip, frames=None,
                               style='sequence', prefix=clip,
                               sequence=f'build/{clip}-sequence', review=f'build/{clip}-review'))
    motion = load_motion(spec["motion"])
    revision = revision if revision is not None else motion.get("revision", 1)
    frames = spec["frames"]
    if frames is None:
        # Match positive std::lround in main.cpp; Python round ties to even.
        frames = max(1, math.floor(motion_duration(motion) / STEP_SECONDS + 0.5))
    resolved = dict(spec)
    resolved.update(frames=frames, revision=revision,
                    sequence=ROOT / spec["sequence"].format(revision=revision),
                    review=ROOT / spec["review"].format(revision=revision), sweeps={})
    if spec["style"] == "grass":
        resolved["manifest"] = MOTIONS / f"{spec['motion']}.motion.json"
        resolved["sweeps"] = {"eye": ROOT / f"build/eye-v{revision}-review",
                              "arm": ROOT / f"build/arm-v{revision}-sweep",
                              "wrist": ROOT / f"build/wrist-v{revision}-sweep"}
    elif spec["style"] == "laptop":
        resolved["manifest"] = "generate"
    else:
        resolved["manifest"] = None
    return resolved


# ---------------------------------------------------------------- native capture

def pose_paths(p):
    """Capture files for the clip's key poses, in manifest order.

    Older review directories stored every capture under the hard-coded grass-
    prefix, so a clip whose own prefix finds nothing falls back to it. That
    keeps the documented revision directories readable without a re-render.
    """
    review = p["review"]
    if not review.is_dir():
        return []
    files = sorted(review.glob(f"{p['prefix']}-[0-9][0-9].png"))
    if not files and p["prefix"] != "grass":
        files = sorted(review.glob("grass-[0-9][0-9].png"))
    return files


def run_exe(args, log=print, watch=None):
    """Run DesktopCompanion.exe and report progress while it works.

    The renderer ships as a Windows GUI build, so it has no usable stdout: even
    with the handle redirected, its own progress prints vanish. Counting the
    PNGs it writes is therefore both the reliable option and the honest one --
    it measures real work rather than intent. A full clip takes roughly a minute
    at four frames per second, and staying silent that long is what made callers
    think the capture had hung.

    `watch` is a `(folder, total, noun)` triple describing the captures to count.
    """
    if not EXE.is_file():
        raise SystemExit(f"Missing {EXE}; build the project first (build/dev.cmd).")
    log("  " + " ".join(["DesktopCompanion.exe"] + [str(a) for a in args]))
    started = time.monotonic()
    options = {}
    if sys.platform == 'win32':
        startup = subprocess.STARTUPINFO()
        startup.dwFlags |= subprocess.STARTF_USESHOWWINDOW
        startup.wShowWindow = 0
        options['startupinfo'] = startup
    process = subprocess.Popen([str(EXE)] + [str(a) for a in args], cwd=BUILD, **options)
    last_report = 0.0
    try:
        while process.poll() is None:
            now = time.monotonic()
            if watch is not None and now - last_report >= 5.0:
                folder, total, noun = watch
                written = len(list(folder.glob("*.png"))) if folder.is_dir() else 0
                # The first frames only appear after the model, shaders and the
                # GL context are up, which takes several seconds on their own.
                stage = f"{written}/{total} {noun}" if written else "warming up (model + GL)"
                log(f"    {stage}, {now - started:.0f}s")
                last_report = now
            time.sleep(0.5)
    except BaseException:
        process.kill()
        process.wait()
        raise
    elapsed = time.monotonic() - started
    if process.returncode != 0:
        raise SystemExit(f"DesktopCompanion.exe failed ({process.returncode}) after {elapsed:.0f}s")
    log(f"    finished in {elapsed:.0f}s")


def ensure_manifest(p, log=print):
    """Return the keyframe manifest for the clip, generating it when needed."""
    if p["manifest"] == "generate":
        p["review"].mkdir(parents=True, exist_ok=True)
        frames = load_motion(p["motion"])["keyframes"]
        poses = [frames[i] for i in (0, 1, 3, 4)]
        poses.append({"time": 9, "label": "连续闭眼",
                      "parameters": {**frames[0]["parameters"], "ParamEyeLOpen": 0, "ParamEyeROpen": 0}})
        poses.append({"time": 10, "label": "回到待机",
                      "parameters": {"ParamBusyLaptop": 0, "ParamEyeLOpen": 1, "ParamEyeROpen": 1}})
        path = p["review"] / "poses.motion.json"
        path.write_text(json.dumps({"keyframes": poses}, ensure_ascii=False, indent=2), encoding="utf8")
        p["manifest"] = path
        log(f"  wrote {path.relative_to(ROOT)}")
    return p["manifest"]


def write_grass_sweep_manifest(kind, p, log=print):
    """Write one grass sweep manifest and return its path (used by --*-manifest)."""
    folder = p["sweeps"][kind]
    folder.mkdir(parents=True, exist_ok=True)
    if kind == "wrist":
        keys = [{"time": row * 3 + col, "label": f"{label}-wrist-{wrist}", "parameters": {
            "ParamArmLA": 0, "ParamArmRA": arm, "ParamElbowLA": 0, "ParamElbowRA": elbow,
            "ParamWristRA": wrist, "ParamGrassReach": reach, "ParamGrassVisible": 1,
            "ParamHandRGrip": 1, "ParamGrassSwing": 0, "ParamGrassTipBend": 0,
            "ParamEyeLOpen": 1, "ParamEyeROpen": 1,
            "ParamAngleX": 0, "ParamAngleY": 0, "ParamAngleZ": 0,
        }} for row, (label, arm, elbow, reach) in enumerate(WRIST_POSES) for col, wrist in enumerate(WRIST_LEVELS)]
    elif kind == "arm":
        keys = [{"time": row * 3 + col, "label": f"elbow-{elbow}-reach-{reach}", "parameters": {
            "ParamArmLA": 0, "ParamArmRA": 35, "ParamElbowLA": 0, "ParamElbowRA": elbow,
            "ParamGrassReach": reach, "ParamGrassVisible": 1, "ParamHandRGrip": 1,
            "ParamGrassSwing": 0, "ParamGrassTipBend": 0,
            "ParamEyeLOpen": 1, "ParamEyeROpen": 1,
            "ParamAngleX": 0, "ParamAngleY": 0, "ParamAngleZ": 0,
        }} for row, elbow in enumerate(ELBOW_LEVELS) for col, reach in enumerate(REACH_LEVELS)]
    else:
        keys = [{"time": row * 5 + col, "label": f"{mode}-{level}", "parameters": {
            "ParamEyeLOpen": float(level), "ParamEyeROpen": float(level), "ParamEyeSmile": row,
            "ParamAngleX": 0, "ParamAngleY": 0, "ParamAngleZ": 0,
        }} for row, mode in enumerate(("open", "smile")) for col, level in enumerate(EYE_LEVELS)]
    path = folder / "poses.motion.json"
    path.write_text(json.dumps({"keyframes": keys}, ensure_ascii=False, indent=2), encoding="utf8")
    log(f"  wrote {path.relative_to(ROOT)}")
    return path


def manifest_poses(manifest):
    """How many key poses a manifest asks the renderer to capture."""
    return len(json.loads(Path(manifest).read_text(encoding="utf8"))["keyframes"])


def clear_captures(folder, pattern):
    """Drop earlier captures so the progress count reflects this run only."""
    if folder.is_dir():
        for stale in folder.glob(pattern):
            stale.unlink()


def capture(p, sweeps=False, log=print):
    """Render the key poses and the full sequence for one clip.

    The grass rig sweeps are diagnostic scans, so they are opt-in via --sweeps;
    without them the capture set matches the earlier scripts exactly.
    """
    manifest = ensure_manifest(p, log)
    if manifest is not None:
        p["review"].mkdir(parents=True, exist_ok=True)
        clear_captures(p["review"], f"{p['prefix']}-[0-9][0-9].png")
        run_exe(["--review-motion", p["review"], manifest, p["prefix"]], log,
                watch=(p["review"], manifest_poses(manifest), "poses"))
    if sweeps:
        for kind in ("wrist", "arm", "eye"):
            if kind in p["sweeps"]:
                sweep = write_grass_sweep_manifest(kind, p, log)
                clear_captures(p["sweeps"][kind], f"{p['prefix']}-[0-9][0-9].png")
                run_exe(["--review-motion", p["sweeps"][kind], sweep, p["prefix"]], log,
                        watch=(p["sweeps"][kind], manifest_poses(sweep), "poses"))
    p["sequence"].mkdir(parents=True, exist_ok=True)
    clear_captures(p["sequence"], "frame-*.png")
    run_exe(["--render-motion", p["sequence"], p["render"]], log,
            watch=(p["sequence"], p["frames"], "frames"))


# ------------------------------------------------------------------- composition

def grass_poses(p):
    """Indexes of the grass keyframes the approval sheet shows."""
    motion = load_motion("grass")
    times = (0.8, 2.0, 3.6, 3.95, 4.35, 5.2) if p["revision"] >= 7 else (0.8, 2.0, 3.6, 5.2)
    return tuple(next(i for i, frame in enumerate(motion["keyframes"]) if frame["time"] == t) for t in times)


def compose_grass(p, log=print):
    motion = load_motion("grass")
    revision = p["revision"]
    poses = grass_poses(p)
    captures = pose_paths(p)
    title = font(24)
    small = font(18)
    sheet = Image.new("RGB", (1120, 104 + ((len(poses) + 1) // 2) * 550), "#e9edf5")
    draw = ImageDraw.Draw(sheet)
    draw.text((28, 18), f"狗尾巴草 · Live2D 草案 v{revision} · 转腕 / 前伸停留", font=title, fill="#1e2c47")
    draw.text((28, 53), f"实际 Cubism 模型渲染 / {review_label(p, '待审批')} / {len(poses)} 个动作关键姿势", font=small, fill="#52617b")
    for cell, key in enumerate(poses):
        x, y = (cell % 2) * 560, 90 + (cell // 2) * 550
        draw.rounded_rectangle((x + 12, y + 8, x + 548, y + 538), radius=18, fill="#f8faff")
        sprite = Image.open(captures[key]).convert("RGBA")
        sprite.thumbnail((488, 488), Image.Resampling.LANCZOS)
        sheet.paste(sprite, (x + (560 - sprite.width) // 2, y + 8), sprite)
        frame = motion["keyframes"][key]
        draw.text((x + 26, y + 495), f"{cell + 1}. {frame['label']}   {frame['time']:g}s", font=small, fill="#243654")
    output = output_folder(p) / f"grass-keyframes-v{revision}.png"
    output.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(output)
    log(f"  wrote {output.relative_to(ROOT)}")
    detail = Image.new("RGB", (1180, 830), "#f8faff")
    detail_draw = ImageDraw.Draw(detail)
    detail_draw.text((24, 16), "表情近景 · 实际 Cubism 渲染 · 待审批", font=title, fill="#243654")
    for cell, key in enumerate((poses[0], poses[1], poses[2], poses[-1])):
        x, y = 24 + cell % 2 * 590, 66 + cell // 2 * 380
        sprite = Image.open(captures[key]).convert("RGBA")
        sprite = sprite.crop((290, 235, 570, 405)).resize((560, 340), Image.Resampling.LANCZOS)
        detail.paste(sprite, (x, y), sprite)
        detail_draw.text((x, y + 342), motion["keyframes"][key]["label"], font=small, fill="#52617b")
    detail_output = output.with_name(f"grass-expression-detail-v{revision}.png")
    detail.save(detail_output)
    log(f"  wrote {detail_output.relative_to(ROOT)}")

    wrist_folder = p["sweeps"].get("wrist")
    if wrist_folder and all((wrist_folder / f"{p['prefix']}-{i:02}.png").is_file() for i in range(9)):
        wrists = Image.new("RGB", (1080, 1230), "#e9edf5")
        wrist_draw = ImageDraw.Draw(wrists)
        wrist_draw.text((20, 12), "腕部摆角 / 袖口与草握点 / 脸侧遮挡 · Native 渲染", font=title, fill="#243654")
        for row, (label, _, _, _) in enumerate(WRIST_POSES):
            for col, angle in enumerate(WRIST_LEVELS):
                x, y = col * 360, 52 + row * 392
                sprite = Image.open(wrist_folder / f"{p['prefix']}-{row * 3 + col:02}.png").convert("RGBA")
                sprite = sprite.resize((350, 350), Image.Resampling.LANCZOS)
                wrists.paste(sprite, (x + 5, y), sprite)
                wrist_draw.text((x + 12, y + 356), f"{label} / 腕角 {angle}°", font=small, fill="#52617b")
        wrists.save(output.with_name(f"wrist-occlusion-v{revision}.png"))
        log(f"  wrote wrist-occlusion-v{revision}.png")

    arm_folder = p["sweeps"].get("arm")
    if arm_folder and all((arm_folder / f"{p['prefix']}-{i:02}.png").is_file() for i in range(9)):
        arms = Image.new("RGB", (1080, 1230), "#e9edf5")
        arm_draw = ImageDraw.Draw(arms)
        arm_draw.text((20, 12), "独立肘关节 / 前伸透视 · Native 渲染 · 待审批", font=title, fill="#243654")
        for row, elbow in enumerate(ELBOW_LEVELS):
            for col, reach in enumerate(REACH_LEVELS):
                x, y = col * 360, 52 + row * 392
                sprite = Image.open(arm_folder / f"{p['prefix']}-{row * 3 + col:02}.png").convert("RGBA")
                sprite = sprite.resize((350, 350), Image.Resampling.LANCZOS)
                arms.paste(sprite, (x + 5, y), sprite)
                arm_draw.text((x + 12, y + 356), f"肘角 {elbow}° / 前伸 {reach}", font=small, fill="#52617b")
        arms.save(output.with_name(f"arm-perspective-v{revision}.png"))
        log(f"  wrote arm-perspective-v{revision}.png")

    eye_folder = p["sweeps"].get("eye")
    if eye_folder and all((eye_folder / f"{p['prefix']}-{i:02}.png").is_file() for i in range(10)):
        eyes = Image.new("RGB", (1400, 510), "#f8faff")
        eye_draw = ImageDraw.Draw(eyes)
        for row, (mode, label) in enumerate((("open", "普通眨眼"), ("smile", "笑眼"))):
            y = row * 255
            eye_draw.text((12, y + 4), label + " · 眼睑形变 / 虹膜遮罩 · Native 渲染", font=small, fill="#243654")
            for col, level in enumerate(EYE_LEVELS):
                eye = Image.open(eye_folder / f"{p['prefix']}-{row * 5 + col:02}.png").convert("RGBA").crop((290, 235, 570, 405))
                eyes.paste(eye, (col * 280, y + 36), eye)
                eye_draw.text((col * 280 + 12, y + 212), f"开合 {level}", font=small, fill="#52617b")
        eyes.save(output.with_name(f"eye-closure-v{revision}.png"))
        log(f"  wrote eye-closure-v{revision}.png")

    gif_from_sequence(p, output.with_name(f"grass-motion-v{revision}.gif"),
                      background="#f8faff", mask_paste=True, palette_indices=(12, 30, 54, 78),
                      dither=Image.Dither.NONE, optimize=False, log=log)


def compose_laptop(p, log=print):
    revision = p["revision"]
    poses = json.loads((p["review"] / "poses.motion.json").read_text(encoding="utf8"))["keyframes"]
    captures = pose_paths(p)
    label = font(22)
    sheet = Image.new("RGB", (1120, 1730), "#e9edf5")
    draw = ImageDraw.Draw(sheet)
    draw.text((24, 16), f"抱电脑工作 v{revision} · 实际 Live2D Native 渲染 · {review_label(p, '动作待审')}", font=label, fill="#243654")
    for i, pose in enumerate(poses):
        x, y = (i % 2) * 560, 60 + (i // 2) * 550
        draw.rounded_rectangle((x + 10, y + 8, x + 550, y + 540), radius=18, fill="#f8faff")
        sprite = Image.open(captures[i]).convert("RGBA")
        sprite.thumbnail((490, 490), Image.Resampling.LANCZOS)
        sheet.paste(sprite, (x + (560 - sprite.width) // 2, y + 8), sprite)
        draw.text((x + 24, y + 500), pose["label"], font=label, fill="#243654")
    output = output_folder(p) / f"busy-laptop-keyframes-v{revision}.png"
    output.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(output)
    log(f"  wrote {output.relative_to(ROOT)}")
    gif_from_sequence(p, output.with_name(f"busy-laptop-motion-v{revision}.gif"),
                      background="#eef3fa", mask_paste=False, palette_indices=None,
                      dither=Image.Dither.FLOYDSTEINBERG, log=log)


def compose_sequence(p, log=print):
    """Approval sheet for a procedural clip: even samples of the real sequence."""
    revision = p["revision"]
    frames = sorted(p["sequence"].glob("frame-*.png"))
    if len(frames) != p["frames"]:
        raise SystemExit(f"{p['name']}: expected {p['frames']} frames, found {len(frames)} in {p['sequence']}")
    # Eight samples read well for a long loop; a short one-shot clip needs a
    # denser sheet, or the peaks of its gesture fall between two samples.
    count = 8 if len(frames) >= 40 else min(len(frames), 12)
    picks = [round(i * (len(frames) - 1) / max(1, count - 1)) for i in range(count)]
    energy = legibility_series(frames)
    # Even sampling is blind to a beat that lasts one or two frames, and that is
    # exactly the beat a reviewer is looking for: a bite or a eureka reads as the
    # clip's whole point and can still fall between two of the eight samples.
    # Clips that ask for it get the sharpest frame pairs appended, so the sheet
    # cannot quietly omit the punch it was rendered to show.
    peaks = p.get("peaks", 0) if len(frames) > 1 else 0
    highlights = []
    if peaks:
        for index in sorted(range(len(energy)), key=lambda i: -energy[i]):
            if len(highlights) >= peaks:
                break
            frame = index + 1  # the animated half of the pair
            if frame in highlights:
                continue
            if frame in picks:
                highlights.append(frame)
                continue
            near = min(picks, key=lambda taken: abs(taken - frame))
            if near in highlights:
                continue  # the same beat, already on the sheet
            if abs(near - frame) <= 2:
                # Even sampling landed beside the beat rather than on it, which
                # is the common case; move that sample onto the beat instead of
                # adding a cell that duplicates its neighbour.
                picks[picks.index(near)] = frame
            else:
                picks.append(frame)
            highlights.append(frame)
        picks = sorted(set(picks))
    label = font(22)
    small = font(16)
    # The sheet keeps the layout the approved sequence sheets were built with;
    # only a clip that asks for peak frames pays for the extra caption line.
    top = 106 if peaks else 90
    sheet = Image.new("RGB", (1120, 104 + ((len(picks) + 1) // 2) * 550), "#e9edf5")
    draw = ImageDraw.Draw(sheet)
    draw.text((28, 18), f"{p['name']} · 实际 Live2D Native 渲染 · {review_label(p, '待审批')}", font=font(24), fill="#1e2c47")
    draw.text((28, 53), f"{len(frames)} 帧整段采样 / {frames[0].name} 起，每帧 1/15 s",
              font=font(18), fill="#52617b")
    if peaks:
        summary = legibility(frames)
        draw.text((28, 76), f"动作能量（按 280 px 实际显示尺寸测） 均值 {summary['energy']} · "
                            f"p90 {summary['p90']} · 峰值 {summary['peak']} · "
                            f"近似静止帧 {summary['still_ratio'] * 100:.1f}%   "
                            f"★ 标记了整段里最强的 {len(highlights)} 拍",
                  font=small, fill="#52617b")
    for cell, index in enumerate(picks):
        x, y = (cell % 2) * 560, top + (cell // 2) * 550
        draw.rounded_rectangle((x + 12, y + 8, x + 548, y + 538), radius=18, fill="#f8faff")
        sprite = Image.open(frames[index]).convert("RGBA")
        sprite.thumbnail((488, 488), Image.Resampling.LANCZOS)
        sheet.paste(sprite, (x + (560 - sprite.width) // 2, y + 8), sprite)
        if peaks:
            marked = index in highlights
            mark = "★ " if marked else ""
            shade = "#243654" if marked else "#52617b"
        else:
            mark, shade = "", "#243654"
        draw.text((x + 26, y + 495), f"{mark}{cell + 1}. {frames[index].name}   {index / 15:.2f}s",
                  font=small, fill=shade)
    output = output_folder(p) / f"{p['name']}-frames-v{revision}.png"
    output.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(output)
    log(f"  wrote {output.relative_to(ROOT)}")
    gif_from_sequence(p, output.with_name(f"{p['name']}-motion-v{revision}.gif"),
                      background="#f8faff", mask_paste=False, palette_indices=None,
                      dither=Image.Dither.NONE, log=log)


def gif_from_sequence(p, target, background, mask_paste, palette_indices, dither, optimize=None, log=print):
    """One palette for the whole cycle keeps the GIF free of colour flicker.

    `mask_paste`, `palette_indices`, `dither` and `optimize` reproduce the
    flattening, palette seeding and save flags of the earlier scripts, so the
    approved GIFs and the new ones are built the same way. Note that passing
    `optimize=False` and omitting it produce different bytes, which is why the
    flag is optional rather than defaulted. This is a review artifact assembled
    from actual Native frames; the desktop pet animates the MOC3 and never
    plays this file.
    """
    sequence = sorted(p["sequence"].glob("frame-*.png"))
    if len(sequence) != p["frames"]:
        log(f"  skip {target.name}: {len(sequence)}/{p['frames']} frames")
        return
    rgb = []
    for path in sequence:
        sprite = Image.open(path).convert("RGBA").resize((420, 420), Image.Resampling.LANCZOS)
        if mask_paste:
            matte = Image.new("RGB", sprite.size, background)
            matte.paste(sprite, (0, 0), sprite)
            rgb.append(matte)
        else:
            matte = Image.new("RGBA", sprite.size, background)
            matte.alpha_composite(sprite)
            rgb.append(matte.convert("RGB"))
    picks = list(palette_indices) if palette_indices is not None else list(range(0, len(rgb), 10))
    overview = Image.new("RGB", (420 * len(picks), 420))
    for i, index in enumerate(picks):
        overview.paste(rgb[index], (i * 420, 0))
    palette = overview.quantize(colors=255)
    frames = [frame.quantize(palette=palette, dither=dither) for frame in rgb]
    options = {"save_all": True, "append_images": frames[1:],
               "duration": [[70, 70, 60][i % 3] for i in range(len(frames))], "loop": 0, "disposal": 2}
    if optimize is not None:
        options["optimize"] = optimize
    frames[0].save(target, **options)
    log(f"  wrote {target.relative_to(ROOT)}")


def compose(p, log=print):
    if p["style"] == "grass":
        compose_grass(p, log)
    elif p["style"] == "laptop":
        compose_laptop(p, log)
    else:
        compose_sequence(p, log)


def compose_desktop_scale(p, log=print):
    """Show six actual 280px frames against light, dark and checker mattes."""
    frames = sorted(p['sequence'].glob('frame-*.png'))
    count = min(6, len(frames))
    if not count:
        raise SystemExit('No Native frames for desktop-scale review.')
    picks = [round(i * (len(frames) - 1) / max(1, count - 1)) for i in range(count)]
    width = count * 300 + 90
    sheet = Image.new('RGB', (width, 1050), '#e9edf5')
    draw = ImageDraw.Draw(sheet)
    draw.text((20, 12), f"{p['name']} · 实际 280px 尺寸 · 本次草稿待复核", font=font(22), fill='#243654')
    draw.text((20, 46), '模型与思考气泡；桌面图标/卷纸/点击分支需另审场景。停顿可以是动作的一部分。',
              font=font(16), fill='#52617b')
    for row, (name, color) in enumerate((('浅色', '#f8faff'), ('深色', '#202634'), ('透明格', None))):
        y = 100 + row * 310
        draw.text((10, y + 125), name, font=font(17), fill='#243654')
        for col, index in enumerate(picks):
            matte = Image.new('RGBA', (PET_WINDOW, PET_WINDOW), color or '#d0d5de')
            if color is None:
                grid = ImageDraw.Draw(matte)
                for cy in range(0, PET_WINDOW, 14):
                    for cx in range(0, PET_WINDOW, 14):
                        if (cx // 14 + cy // 14) % 2:
                            grid.rectangle((cx, cy, cx + 13, cy + 13), fill='#eff1f5')
            with Image.open(frames[index]) as source:
                sprite = source.convert('RGBA').resize((PET_WINDOW, PET_WINDOW), Image.Resampling.LANCZOS)
            matte.alpha_composite(sprite)
            x = 90 + col * 300
            sheet.paste(matte.convert('RGB'), (x, y))
            draw.text((x + 8, y + 282), f'{index / 15:.2f}s · 整段采样', font=font(16), fill='#52617b')
    target = output_folder(p) / f"{p['name']}-desktop-scale.png"
    target.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(target)
    log(f'  wrote {target.relative_to(ROOT)}')
    return target


# --------------------------------------------------------------------- validation

def alpha_channel(path):
    return Image.open(path).convert("RGBA").getchannel("A")


def border_max(alpha):
    width, height = alpha.size
    return max(
        alpha.crop((0, 0, width, 1)).getextrema()[1],
        alpha.crop((0, height - 1, width, height)).getextrema()[1],
        alpha.crop((0, 0, 1, height)).getextrema()[1],
        alpha.crop((width - 1, 0, width, height)).getextrema()[1],
    )


def floor_row(alpha):
    solid = alpha.point(lambda value: 255 if value > ALPHA_THRESHOLD else 0)
    box = solid.getbbox()
    assert box is not None, "Frame has no opaque pixel"
    return box[3] - 1


# The pet is shown in a fixed 280 px window (src/PetWindow.cpp), while the
# approval captures are 840 px. A change that reads on a sheet can be invisible
# on screen, so every figure is re-measured at the window size before it is
# called expressive.
PET_WINDOW = 280
STILL_CUTOFF = 0.5  # mean grey level per frame pair; below this a viewer sees a still


def legibility_series(frames):
    """Per frame-pair motion energy, at the size the pet is actually shown.

    Consecutive frames are scaled to the window size and composited over one
    flat colour, then compared pixel by pixel. A viewer reads a pair below
    `STILL_CUTOFF` as frozen, which is what "看不出在做什么动作" means
    numerically; the size of a difference says how far the visible pixels
    travelled.
    """
    series = []
    previous = None
    for path in frames:
        image = Image.open(path).convert("RGBA").resize((PET_WINDOW, PET_WINDOW), Image.LANCZOS)
        flat = Image.new("RGB", image.size, (96, 96, 96))
        flat.paste(image, (0, 0), image)
        grey = flat.convert("L")
        if previous is not None:
            series.append(ImageStat.Stat(ImageChops.difference(grey, previous)).mean[0])
        previous = grey
    return series


def legibility(frames, cutoff=STILL_CUTOFF):
    """Summarise a capture set's motion energy in one line."""
    ordered = sorted(legibility_series(frames))
    count = len(ordered)
    if not count:
        # A one-frame pose has no frame pair from which to measure motion.
        return {"window": PET_WINDOW, "energy": None, "median": None,
                "p90": None, "peak": None, "still_ratio": None}
    return {
        "window": PET_WINDOW,
        "energy": round(sum(ordered) / count, 3),
        "median": round(ordered[count // 2], 3),
        "p90": round(ordered[min(count - 1, int(count * 0.9))], 3),
        "peak": round(ordered[-1], 3),
        "still_ratio": round(sum(1 for value in ordered if value < cutoff) / count, 3),
    }


def validate(p, expected_poses=None, max_floor_drift=4):
    """Check native captures for clipping and a moving floor, then report."""
    frames = sorted(p["sequence"].glob("frame-*.png"))
    poses = pose_paths(p)
    assert len(frames) == p["frames"], f"{p['name']}: expected {p['frames']} sequence frames, got {len(frames)}"
    if expected_poses is not None:
        assert len(poses) == expected_poses, f"{p['name']}: expected {expected_poses} poses, got {len(poses)}"
    frame_set = set(frames)
    floors = []
    for path in frames + poses:
        alpha = alpha_channel(path)
        assert not border_max(alpha), path
        if path in frame_set:
            floors.append(floor_row(alpha))
    drift = max(floors) - min(floors)
    # Poses that put shoes below hair, skirt and tail are checked through their
    # alpha contour, rather than trusting the renderer's own offset.
    assert drift <= max_floor_drift, f"{p['name']} floor drift: {min(floors)}..{max(floors)}"
    report = {"clip": p["name"], "revision": p["revision"],
              "sequence_frames": len(frames), "native_poses": len(poses),
              "alpha_border_failures": 0, "floor_y_range": [min(floors), max(floors)],
              "floor_drift_pixels": drift}
    report["legibility"] = legibility(frames)
    if p.get('draft'):
        report['metric_policy'] = 'diagnostic_only; quiet holds do not fail approval'
        report['capture_scope'] = 'native_model_and_thought_bubble'
    target = p["sequence"].parent / f"{p['name']}-review-check.json"
    target.write_text(json.dumps(report, indent=2), encoding="utf8")
    print(json.dumps(report))
    return report


# ---------------------------------------------------------------------------- CLI

def main(argv=None):
    parser = argparse.ArgumentParser(description="Render and compose a motion approval sheet.")
    parser.add_argument("clip", choices=available_clips(), metavar="clip",
                        help="motion to review: " + ", ".join(available_clips()))
    parser.add_argument("--revision", type=int, default=None,
                        help="override the revision recorded in the motion file")
    parser.add_argument("--no-render", action="store_true", help="compose from existing captures")
    parser.add_argument("--draft", action="store_true",
                        help="fresh isolated review run; preserve approved artifacts and record inputs")
    parser.add_argument("--sweeps", action="store_true",
                        help="also render the grass eye/arm/wrist diagnostic sweeps")
    parser.add_argument("--validate", action="store_true", help="check captures after composing")
    parser.add_argument("--max-floor-drift", type=int, default=4, help="allowed floor drift in pixels")
    args = parser.parse_args(argv)
    if args.draft and args.no_render:
        parser.error('--draft requires fresh Native captures; existing files have no verified provenance')
    p = profile(args.clip, args.revision)
    print(f"{p['name']} v{p['revision']}: {p['frames']} frames, style={p['style']}")
    evidence = None
    if not args.no_render:
        # The manifest is read from source; the exe loads build/assets. Never
        # silently review one dataset and label it as the other.
        records = deployment_snapshot()
        subprocess.run([sys.executable, str(ROOT / 'tools/validate_live2d_assets.py')], check=True)
        if args.draft:
            p = new_draft_profile(p)
            evidence = record_session(p, records)
            print(f"  isolated draft: {p['run']}")
        print("  native capture runs at a few frames per second; expect about a minute")
    try:
        if not args.no_render:
            capture(p, sweeps=args.sweeps)
        compose(p)
        if args.draft:
            compose_desktop_scale(p)
        if args.validate or args.draft:
            report = validate(p, max_floor_drift=args.max_floor_drift)
            if evidence is not None:
                evidence['validation'] = report
        if evidence is not None:
            finish_session(p, evidence)
            print('  draft ready; review approval remains pending')
    except BaseException as error:
        if evidence is not None:
            evidence.update(capture_status='failed', error=str(error))
            write_session(p, evidence)
        raise
    return 0


if __name__ == "__main__":
    sys.exit(main())
